//User
export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST'
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS'
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE'
export const GET_CATEGORIES_RESET = 'GET_CATEGORIES_RESET'

//Admin
export const GET_ADMIN_CATEGORIES_REQUEST = 'GET_ADMIN_CATEGORIES_REQUEST'
export const GET_ADMIN_CATEGORIES_SUCCESS = 'GET_ADMIN_CATEGORIES_SUCCESS'
export const GET_ADMIN_CATEGORIES_FAILURE = 'GET_ADMIN_CATEGORIES_FAILURE'
export const GET_ADMIN_CATEGORIES_RESET = 'GET_ADMIN_CATEGORIES_RESET'

export const GET_ADMIN_CATEGORY_DETAIL_REQUEST =
    'GET_ADMIN_CATEGORY_DETAIL_REQUEST'
export const GET_ADMIN_CATEGORY_DETAIL_SUCCESS =
    'GET_ADMIN_CATEGORY_DETAIL_SUCCESS'
export const GET_ADMIN_CATEGORY_DETAIL_FAILURE =
    'GET_ADMIN_CATEGORY_DETAIL_FAILURE'
export const GET_ADMIN_CATEGORY_DETAIL_RESET = 'GET_ADMIN_CATEGORY_DETAIL_RESET'

export const CREATE_CATEGORY_REQUEST = 'CREATE_CATEGORY_REQUEST'
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS'
export const CREATE_CATEGORY_FAILURE = 'CREATE_CATEGORY_FAILURE'
export const CREATE_CATEGORY_RESET = 'CREATE_CATEGORY_RESET'

export const UPDATE_CATEGORY_REQUEST = 'UPDATE_CATEGORY_REQUEST'
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS'
export const UPDATE_CATEGORY_FAILURE = 'UPDATE_CATEGORY_FAILURE'
export const UPDATE_CATEGORY_RESET = 'UPDATE_CATEGORY_RESET'

export const DELETE_CATEGORY_REQUEST = 'DELETE_CATEGORY_REQUEST'
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS'
export const DELETE_CATEGORY_FAILURE = 'DELETE_CATEGORY_FAILURE'
export const DELETE_CATEGORY_RESET = 'DELETE_CATEGORY_RESET'
