export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST'
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_RESET = 'CREATE_ORDER_RESET'
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL'

export const MY_ORDERS_REQUEST = 'MY_ORDERS_REQUEST'
export const MY_ORDERS_SUCCESS = 'MY_ORDERS_SUCCESS'
export const MY_ORDERS_FAIL = 'MY_ORDERS_FAIL'

export const ORDER_DETAIL_REQUEST = 'ORDER_DETAIL_REQUEST'
export const ORDER_DETAIL_SUCCESS = 'ORDER_DETAIL_SUCCESS'
export const ORDER_DETAIL_FAIL = 'ORDER_DETAIL_FAIL'

//Admin
export const GET_ADMIN_ORDERS_REQUEST = 'GET_ADMIN_ORDERS_REQUEST'
export const GET_ADMIN_ORDERS_SUCCESS = 'GET_ADMIN_ORDERS_SUCCESS'
export const GET_ADMIN_ORDERS_FAILURE = 'GET_ADMIN_ORDERS_FAILURE'
export const GET_ADMIN_ORDERS_RESET = 'GET_ADMIN_ORDERS_RESET'

export const GET_ADMIN_ORDERS_DETAIL_REQUEST = 'GET_ADMIN_ORDERS_DETAIL_REQUEST'
export const GET_ADMIN_ORDERS_DETAIL_SUCCESS = 'GET_ADMIN_ORDERS_DETAIL_SUCCESS'
export const GET_ADMIN_ORDERS_DETAIL_FAILURE = 'GET_ADMIN_ORDERS_DETAIL_FAILURE'
export const GET_ADMIN_ORDERS_DETAIL_RESET = 'GET_ADMIN_ORDERS_DETAIL_RESET'

export const UPDATE_ORDER_STATUS_REQUEST = 'UPDATE_ORDER_STATUS_REQUEST'
export const UPDATE_ORDER_STATUS_SUCCESS = 'UPDATE_ORDER_STATUS_SUCCESS'
export const UPDATE_ORDER_STATUS_FAILURE = 'UPDATE_ORDER_STATUS_FAILURE'
export const UPDATE_ORDER_STATUS_RESET = 'UPDATE_ORDER_STATUS_RESET'
