//User
export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE'
export const GET_PRODUCTS_RESET = 'GET_PRODUCTS_RESET'

export const PRODUCT_DETAIL_REQUEST = 'PRODUCT_DETAIL_REQUEST'
export const PRODUCT_DETAIL_SUCCESS = 'PRODUCT_DETAIL_SUCCESS'
export const PRODUCT_DETAIL_FAILURE = 'PRODUCT_DETAIL_FAILURE'

//Admin
export const GET_ADMIN_PRODUCTS_REQUEST = 'GET_ADMIN_PRODUCTS_REQUEST'
export const GET_ADMIN_PRODUCTS_SUCCESS = 'GET_ADMIN_PRODUCTS_SUCCESS'
export const GET_ADMIN_PRODUCTS_FAILURE = 'GET_ADMIN_PRODUCTS_FAILURE'
export const GET_ADMIN_PRODUCTS_RESET = 'GET_ADMIN_PRODUCTS_RESET'

export const GET_ADMIN_PRODUCT_DETAIL_REQUEST =
    'GET_ADMIN_PRODUCT_DETAIL_REQUEST'
export const GET_ADMIN_PRODUCT_DETAIL_SUCCESS =
    'GET_ADMIN_PRODUCT_DETAIL_SUCCESS'
export const GET_ADMIN_PRODUCT_DETAIL_FAILURE =
    'GET_ADMIN_PRODUCT_DETAIL_FAILURE'
export const GET_ADMIN_PRODUCT_DETAIL_RESET = 'GET_ADMIN_PRODUCT_DETAIL_RESET'

export const CREATE_PRODUCT_REQUEST = 'CREATE_PRODUCT_REQUEST'
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS'
export const CREATE_PRODUCT_FAILURE = 'CREATE_PRODUCT_FAILURE'
export const CREATE_PRODUCT_RESET = 'CREATE_PRODUCT_RESET'

export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST'
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS'
export const UPDATE_PRODUCT_FAILURE = 'UPDATE_PRODUCT_FAILURE'
export const UPDATE_PRODUCT_RESET = 'UPDATE_PRODUCT_RESET'

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST'
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_FAILURE = 'DELETE_PRODUCT_FAILURE'
export const DELETE_PRODUCT_RESET = 'DELETE_PRODUCT_RESET'
